language: java

before_script:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install mono-mcs -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxjava
  - haxelib install hxcs

script:
  - ant
